### PR TITLE
wip: Storage mods

### PR DESCRIPTION
**Pull request by jakubwitowski-silvair**
Storage functionality updated to the current api

### CODE REVIEW

**Comment by michallowasrzechonek-silvair** [comment]
Indentation!

**Comment by michallowasrzechonek-silvair** [comment]
```
WARNING: Missing a blank line after declarations
#51: FILE: mesh/mesh-db.c:975:
+		char int_as_str[6];
+		sprintf(int_as_str, "%u", ele_nr);

WARNING: line over 80 characters
#57: FILE: mesh/mesh-db.c:977:
+		if(!json_object_object_get_ex(jelements, int_as_str, &jelement)) {

ERROR: space required before the open parenthesis '('
#57: FILE: mesh/mesh-db.c:977:
+		if(!json_object_object_get_ex(jelements, int_as_str, &jelement)) {

WARNING: Missing a blank line after declarations
#65: FILE: mesh/mesh-db.c:983:
+		int elementIndex;
+		if(!get_int(jelement, "elementIndex", &elementIndex))

ERROR: space required before the open parenthesis '('
#65: FILE: mesh/mesh-db.c:983:
+		if(!get_int(jelement, "elementIndex", &elementIndex))

ERROR: space required before the open parenthesis '('
#88: FILE: mesh/mesh-db.c:1007:
+		if(!json_object_object_get_ex(jelement, "models", &jmodels))

ERROR: space required before the open parenthesis '('
#96: FILE: mesh/mesh-db.c:1013:
+		if(!parse_models(jmodels, ele))

WARNING: braces {} are not necessary for any arm of this statement
#159: FILE: mesh/mesh-db.c:1177:
+	if (!mod->vendor) {
[...]
 	else {
[...]

ERROR: space required before the open parenthesis '('
#223: FILE: mesh/mesh-db.c:1400:
+	if(!mesh_db_write_iv_index(jnode, node->iv_index, node->iv_update))

ERROR: space required before the open parenthesis '('
#230: FILE: mesh/mesh-db.c:1404:
+	if(!add_key(jnode, "UUID", node->uuid))

ERROR: space required before the open parenthesis '('
#237: FILE: mesh/mesh-db.c:1408:
+	if(!mesh_db_write_bool(jnode, "beacon", modes->beacon))

WARNING: line over 80 characters
#243: FILE: mesh/mesh-db.c:1412:
+	json_object_object_add(jnode, "defaultTTL", json_object_new_int(node->ttl));

ERROR: space required before the open parenthesis '('
#249: FILE: mesh/mesh-db.c:1415:
+	if(!mesh_db_write_device_key(jnode, node->dev_key))

ERROR: space required before the open parenthesis '('
#259: FILE: mesh/mesh-db.c:1421:
+	if(!jelements)

ERROR: that open brace { should be on the previous line
#269: FILE: mesh/mesh-db.c:1426:
+	for(int idx = 0; entry; entry = entry->next, idx++)
+	{

ERROR: space required before the open parenthesis '('
#269: FILE: mesh/mesh-db.c:1426:
+	for(int idx = 0; entry; entry = entry->next, idx++)

WARNING: line over 80 characters
#285: FILE: mesh/mesh-db.c:1437:
+		mesh_db_write_uint16_hex(jsub_elements, "location", ele->location);

WARNING: line over 80 characters
#288: FILE: mesh/mesh-db.c:1439:
+		json_object_object_add(jelements, &int_as_str[0], jsub_elements);

ERROR: space required before the open parenthesis '('
#294: FILE: mesh/mesh-db.c:1442:
+		if(l_queue_isempty(ele->models))

ERROR: space required before the open parenthesis '('
#304: FILE: mesh/mesh-db.c:1447:
+		if(!jmodels) {

ERROR: space required before the open parenthesis '('
#323: FILE: mesh/mesh-db.c:1459:
+	if(!mesh_db_write_bool(jnode, "friend", modes->friend))

ERROR: space required before the open parenthesis '('
#328: FILE: mesh/mesh-db.c:1462:
+	if(!mesh_db_write_bool(jnode, "lowPower", modes->low_power))

ERROR: space required before the open parenthesis '('
#335: FILE: mesh/mesh-db.c:1466:
+	if(!add_key(jnode, "net_key", node->net_key))

WARNING: line over 80 characters
#542: FILE: mesh/storage.c:517:
+	const uint8_t uuid_str_len = (2 * NODE_UUID_LEN) + NUM_OF_SEP_IN_UUID_STR + 1;
```

**Comment by michallowasrzechonek-silvair** [comment]
https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/scripts/checkpatch.pl

**Comment by jakubwitowski-silvair** [comment]
Fixed

**Pull request closed without merging**
